name: Sync to Hugging Face

on:
  push:
    branches:
      - main  # 每次 main 分支有變更時執行

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git clone https://huggingface.co/spaces/neako0230/scholarly-search-app
          cd scholarly-search-app
          rm -rf *
          cp -r ../project2/* .
          git config --global user.email "your-email@example.com"
          git config --global user.name "your-github-username"
          git add .
          git commit -m "Sync from GitHub to Hugging Face"
          git push
